/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.lanhouseapp.frames;
import br.lanhouseapp.listeners.MainFrameListener;
import br.lanhouseapp.listeners.UsuarioListener;

/**
 *
 * @author juanvmr
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainJFrame() {
        initComponents();
        addFrames();
        addListeners();
    }
    
    private void addFrames(){
        admin = new AdminJInternalFrame();
        admin.setVisible(false);
        this.add(admin);
        
        usuario = new UsuarioJInternalFrame();
        usuario.setVisible(false);
        this.add(usuario);
        
        novavenda = new NovaVendaJInternalFrame();
        novavenda.setVisible(false);
        this.add(novavenda);
        
        maquinas = new MaquinasJInternalFrame();
        maquinas.setVisible(false);
        this.add(maquinas);
    }
    
    private void addListeners(){
        listener = new MainFrameListener(this);
        
        GerenciarAdminJMenuItem.addActionListener(listener);
        GerenciarMaquinasJMenuItem.addActionListener(listener);
        GerenciarUsuarioJMenuItem.addActionListener(listener);
        NovaVendaJMenuItem.addActionListener(listener);
        RelatorioVendaJMenuItem.addActionListener(listener);
        SobreJMenuItem.addActionListener(listener);
        
        SobreJMenuItem.setActionCommand(".main.sobreButton");
        GerenciarAdminJMenuItem.setActionCommand(".main.gerenciarAdminButton");
        GerenciarMaquinasJMenuItem.setActionCommand(".main.gerenciarMaquinasButton");
        GerenciarUsuarioJMenuItem.setActionCommand(".main.gerenciarUsuarioButton");
        NovaVendaJMenuItem.setActionCommand(".main.novaVendaButton");
        RelatorioVendaJMenuItem.setActionCommand(".main.relatorioVendaButton");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        AdminMenu = new javax.swing.JMenu();
        GerenciarAdminJMenuItem = new javax.swing.JMenuItem();
        UsuarioMenu = new javax.swing.JMenu();
        GerenciarUsuarioJMenuItem = new javax.swing.JMenuItem();
        MaquinasMenu = new javax.swing.JMenu();
        GerenciarMaquinasJMenuItem = new javax.swing.JMenuItem();
        VendasMenu = new javax.swing.JMenu();
        NovaVendaJMenuItem = new javax.swing.JMenuItem();
        RelatorioVendaJMenuItem = new javax.swing.JMenuItem();
        SobreMenu = new javax.swing.JMenu();
        SobreJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminMenu.setText("Admin");

        GerenciarAdminJMenuItem.setText("Gerenciar");
        AdminMenu.add(GerenciarAdminJMenuItem);

        jMenuBar1.add(AdminMenu);

        UsuarioMenu.setText("Usuário");

        GerenciarUsuarioJMenuItem.setText("Gerenciar");
        UsuarioMenu.add(GerenciarUsuarioJMenuItem);

        jMenuBar1.add(UsuarioMenu);

        MaquinasMenu.setText("Máquinas");

        GerenciarMaquinasJMenuItem.setText("Gerenciar");
        MaquinasMenu.add(GerenciarMaquinasJMenuItem);

        jMenuBar1.add(MaquinasMenu);

        VendasMenu.setText("Vendas");

        NovaVendaJMenuItem.setText("Nova venda");
        VendasMenu.add(NovaVendaJMenuItem);

        RelatorioVendaJMenuItem.setText("Relatório");
        VendasMenu.add(RelatorioVendaJMenuItem);

        jMenuBar1.add(VendasMenu);

        SobreMenu.setText("Sobre");

        SobreJMenuItem.setText("Sobre nós");
        SobreMenu.add(SobreJMenuItem);

        jMenuBar1.add(SobreMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    
    NovaVendaJInternalFrame novavenda;
    MaquinasJInternalFrame maquinas;
    UsuarioJInternalFrame usuario;
    AdminJInternalFrame admin;
    MainFrameListener listener;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AdminMenu;
    private javax.swing.JMenuItem GerenciarAdminJMenuItem;
    private javax.swing.JMenuItem GerenciarMaquinasJMenuItem;
    private javax.swing.JMenuItem GerenciarUsuarioJMenuItem;
    private javax.swing.JMenu MaquinasMenu;
    private javax.swing.JMenuItem NovaVendaJMenuItem;
    private javax.swing.JMenuItem RelatorioVendaJMenuItem;
    private javax.swing.JMenuItem SobreJMenuItem;
    private javax.swing.JMenu SobreMenu;
    private javax.swing.JMenu UsuarioMenu;
    private javax.swing.JMenu VendasMenu;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
